version: "3.7"

services:
  nexlist-app:
    build:
      context: ./nexlist-app      # Dockerfile이 위치한 디렉토리 경로
      dockerfile: Dockerfile      # Dockerfile 이름 (생략 가능, 기본값은 'Dockerfile')
    container_name: nexlist
    ports:
      - "5000:5000"