services:
  # Nginx: TLS Termination & Reverse Proxy
  proxy:
    image: nginx
    container_name: proxy
    ports:
      - 80:80  # HTTP(80)
      - 443:443  # HTTPS(443)
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
        
    depends_on:
      - frontend
      - backend

  # HTTPS 인증서 발급 및 갱신
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./proxy/certbot/conf:/etc/letsencrypt
      - ./proxy/certbot/www:/var/www/certbot
    depends_on:
      - proxy
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # React
  frontend:
    build:
      context: ./frontend
    expose:
      - 80

  # FastAPI
  backend:
    build:
      context: ./server
    volumes:
      - type: bind
        source: ./server
        target: /app
    env_file:
      - ./server/.env.${NEXLIST_ENV}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # MySQL
  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: nexlist
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
